### ISSUE TITLE
yosemite branch fails on 10.10 with bundled PyObjC

### ISSUE THREAD

**Issue by justvanrossum** [typesupply/vanilla#38]
This is probably what @anthrotype meant what could possibly go wrong...

```
>>> import vanilla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/just/code/git/vanilla/Lib/vanilla/__init__.py", line 3, in <module>
    from vanilla.vanillaBrowser import ObjectBrowser
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaBrowser.py", line 172, in <module>
    class PythonItem(AppKit.NSObject):
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaBrowser.py", line 254, in PythonItem
    @objc.python_method
AttributeError: 'module' object has no attribute 'python_method'
```

```python
>>> objc.__version__
'2.5.1'
```

**Comment by justvanrossum** [comment]
I think I know how to fix it.
