### ISSUE TITLE
Level Indicator example fails with missing module

### ISSUE THREAD

**Issue by frankrolf** [typesupply/vanilla#57]
The example for the level indicator (found here http://ts-vanilla.readthedocs.io/en/latest/objects/List.html#list-item-cells) fails in RF3 but works in RF1.8.
I assume it has to do with the import cleanups done around 1d30cfd and fc61ccb.

This is from RF3:
```
Traceback (most recent call last):
  File "<untitled>", line 30, in <module>
  File "<untitled>", line 18, in __init__
  File "/Applications/RoboFontPy3.app/Contents/Resources/lib/python3.6/vanilla/vanillaLevelIndicator.py", line 272, in LevelIndicatorListCell
NameError: name 'NSLevelIndicatorCell' is not defined
```

**Comment by justvanrossum** [comment]
That was indeed the issue. Thanks, Frank!
